apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-api
  namespace: backend
spec:
  replicas: 15
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api
    spec:
      containers:
      - name: poi-api
        image: tripinsights/poi:1.0
        resources:
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            value: 123#@!qweEWQ
          - name: SQL_SERVER
            value: sqltestdb
          - name: SQL_USER
            value: sa
          - name: ASPNETCORE_ENVIRONMENT
            value: local
