apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: tripinsights/webapp:1.0
        resources:
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-api:80
          - name: TRIPS_API_ENDPOINT
            value: http://trips-api.svc.cluster.local
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: BING_MAPS_KEY
            value: ""
