apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-api
  namespace: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: userjava-api
  template:
    metadata:
      labels:
        app: userjava-api
    spec:
      containers:
      - name: userjava-api
        image: tripinsights/user-java:1.0
        resources:
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            value: 123#@!qweEWQ
          - name: SQL_SERVER
            value: sqltestdb
          - name: SQL_USER
            value: sa
